version: "3"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    ports:
     - 3307:3307
    environment:
     - MYSQL_ROOT_PASSWORD=0000
     - MYSQL_DATABASE=achathadb
     - MYSQL_USER=root
     - MYSQL_PASSWORD=


  spring_app:
    image: hazembaccouch/alpine
    container_name: achatspring
    restart: on-failure
    environment:
     - spring.datasource.url=jdbc:mysql://mysqldb:3307/achathadb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
     - 8089:8089
    depends_on:
     - mysqldb
